### PR TITLE
Adds support to latest Intellij Version

### PR DESCRIPTION
**Pull request by paulochang**
As far as I can tell there's no major changes in IntelliJ so a simple update of the metadata should be enough.

### CODE REVIEW

**Comment by paulochang** [comment]
Fixes #246

**Comment by koha26** [comment]
Unfortunately, PR doesn’t pass verification. There are incompatible change. Will check later today. Thank you for the PR.

**Comment by paulochang** [comment]
Yeah, I added the last version of the IDE to the list of the PluginVerifier and it failed... but at least now there's a list of deprecated api's to fix... I might take a look later.. maybe
In any case, thanks for keeping an eye :)

**Comment by koha26** [comment]
Fixed in the https://github.com/aemtools/aemtools/pull/248.

**Pull request closed without merging**
